default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rob
  password: rob

development:
  <<: *default
  database: moves_points_development

test:
  <<: *default
  database: moves_points_test

production:
  <<: *default
  database: moves_points_production
